### ISSUE TITLE
Can't get passthrough to work

### ISSUE THREAD

**Issue by brenosabino** [ddurdle/Python-GoogleDrive-VideoStream#55] opened 2018-05-11 20:21 UTC
I can't get passthrough to work even though its enabled in the webui settings. Ive tried in both windows and linux. And im trying to play the original version, the file plays but it streams from the emby server instead of directly from google drive.

This is the log of the script while playing - https://pastebin.com/XErEAK0E

**Comment by ddurdle** [comment] 2018-05-11 22:26
What is the emby device being played back on?

**Comment by brenosabino** [comment] 2018-05-11 23:18
in this case it was in a windows pc using the web interface in chrome. Ive also tried on android with same results. on kodi it seemed to work once and the script didnt show any errors that time but i cant get it working again.

**Comment by ddurdle** [comment] 2018-05-12 00:10
with regards to Android, newer versions of android emby prevent Direct Play and FORCE playback of any HTTP through server, by Emby design. 

I will mark this to investigate as perhaps something has broken in latest build to cause the problem you are seeing.  It should definitely Direct Play in chrome and Kodi.

Which version of Emby server?

**Comment by brenosabino** [comment] 2018-05-12 00:11
3.4.1.0

**Comment by ddurdle** [comment] 2018-05-12 05:07
should be fixed now in master and 0.1.20

**Comment by brenosabino** [comment] 2018-05-12 17:05
i did a fresh install and it did work on kodi again. and it did work on the web player after i disabled subtitle extraction and all the transcode options for the user, only without audio because the original video had dts codec. On the android as you said it forces the playback through the server. But the strange thing is that after this happens it keeps playing from the server even on kodi, and I keep getting these broken pipe errors on the script output. 

Also why cant the transcode versions be direct played? It would be a better suit for the web player that cant decode the audio.

**Comment by ddurdle** [comment] 2018-05-12 20:36
I'll be working on a wiki guide with optimum steps for playback of Google Drive content in Emby.

At this point, yes, you should disable the subtitle "on the fly" extraction, located in the Transcoding settings pane in Emby.  I had an Emby developer confirm this will cause huge performance hits on an emby server and affect playback startup performance.

In a user's profile, in "transcoding section", yes, only option 1 and 4 should be enabled (audio and video transcoding should be disabled).  I'm testing an additional module I wrote for Emby that will let the user enable all 4 options so that the "quality selector" will appear for them when they playback, so that they can toggle between the different transcodings, and those transcodings would be provided via Google Drive transcoding.  They would appear to the user as "transocding", where in reality they will be "Direct Stream" remux.  So the CPU impact on the Emby server would be 0.5-1% during playback.

The pipe errors are just showing the end user abandoned the connection.  This is in an early stage of release so I leave debugging for errors on, so that all possible error conditions are being reported.  It is intended as the code matures, these will be silenced.

Emby is actually stepping away from supporting Direct Play at all, citing concerns that their apps will be removed from the various app stores for violating the app store policies (Apple, Microsoft, Android, Samsung, Roku, etc).  Earlier versions of the Emby client apps will do Direct Play.  But the most current Emby app in the iOS and Google Play store force streams to be passed through the Emby server even if I'm trying to direct them to Direct Play.  You will even see the console status in Emby briefly go to Direct Play for a second before Emby forces the stream through the server.  The Roku and some of the TV apps (Samsung, LG, etc) haven't been updated yet to block Direct Play (the Emby Beta versions have).  For your iOS/Android device, you at least have the ability to side-load the older version.  Don't expect any change in decision to reverse this.  I believe the concern is that these app stores don't want to allow piracy, and the app stores interpret piracy being any app that allows the user to load media to playback from outside it's own ecosystem (that is, from web servers outside of it's own Emby server).  By enforcing all playback data through the Emby server the client is connected to, it satisfies the requirement that it is media playback client for media personally owned by the end-user.

With that said, Emby theatre, and mobile browser or web browsers versions will continue to support Direct Play since they are not tied to an app store. 

Now to get to your finally question about transcoding.  Google modified the logic to their transcoding service about 2-2.5 years ago by adding an additional layer of authentication following a CORS implementation.  Their idea here was to fend off all these illegal media sharing sites that began posting Google Drive videos for playbackback on their website.

I opened a request prior with Emby to support CORS, but considering their new stance on Direct Playback, even if they decided to implement CORS, the streams would still be forced to playback through the Emby server to satisfy the app store requirements. 

In the end, a moderate sized VPS could host a library of thousands of movies to a few hundred concurrent users because the data itself was streamed direct from Google via Direct Play.  With Direct Stream, I have rigged together some code that would allow a weak powered VPS to stream concurrently between 1-2 hundred users.  There are some advantages to Direct Streaming, as I'll be able to remux on the fly different sound tracks, different audio codecs, and different subtitle tracks.  This part I'm working on and testing on my Emby servers (not for public release yet).  The goal here is that a user who is playing back a 4K movie with TrueHD on a device that neither supports 4K or True HD will be able to playback via Direct Stream a 1080p video with an AC3 audio track and perhaps an embedded subtitle track from the original file, all without incurring any encoding on the Emby server (albeit the bytes will stream through it).

**Comment by ddurdle** [comment] 2018-05-17 13:59
With Direct Play, no bandwidth is being consumed down or up by the Emby server for playback of the video (other then displaying the fanart images to the user).  Direct Play will only work Google Drive "original" quality playback and Google Photos Video transcode playback.  It will not work with Google Drive transcode.  Emby is stepping away from support Direct Play.  It is already removed from their latest apps (ios,android,roku, samsumg, microsft, lg, etc) being deployed.  It will continue to work only with web browser (chrome) playback, including mobile browser and KODI / MrMC.  Unsure about status of Emby Theatre with regards to Direct Play.  For playback in the emby apps, you'd need to stay on an older version (by side-loading them, as in not installing them or updating them from the app store).  On platforms like Roku, Samsung, LG, etc, you can't side-load apps, so you at the mercy of accepting Direct Play goodbye on those platforms.

With Direct Stream, bandwidth is consumed on down and up by the Emby server for playback of the video.  However, minimal CPU is consumed (0.5-1%).  The latest Emby apps will drop down the Direct Play to Direct Stream.  Because this is being forced on the user, Direct Stream does provide some additional benefits at the cost of the bandwidth.  Newer versions of the plugin being tested will allow users to remux different audio tracks, subtitles, etc into the Direct Stream.  It will also be possible to blend an audio track from original quality with the video output of a Google transcode version.  You'll be able to enjoy the perks of watching a 4K video transcoded to a lower resolution without incurring CPU usage on the emby server (as in, not killing the server).  But the bandwidth costs will be there.

It is important to note.  The default behaviour in Emby is to slurp the entire file.  Let's take for instance and extreme case.  A user tries to playback a 100GB video file.  Via Direct Stream, Emby will immediately try to slurp the entire video down.  For simplification, let's say it takes 10 seconds to download the entire file.  If for some reason the user watches 10 seconds and decides the movie isn't to his liking, and he cancels it, you would have incurred 100GB of bandwidth costs downloading (ingress) to the emby server (including the storage on the server itself to store it temporarily), and the upload costs (egress) to playback 10 seconds of that video.  Another very special note.  If the user is playing back a Google Drive transcode version of the video, this situation would not happen.  Google automatically controls the rate of download.  So your Emby server will only be so many seconds ahead in the download.  Thus, you only consume down in bandwidth in what the user actually watches.  So if he aborts that 100GB video after 10 seconds, the bandwidth consumed by the emby server will be only 10-20 seconds worth of video.  Thus, this controls your bandwidth costs, if you are paying for metered bandwidth.

If you are using Google Compute Engine, down (ingress) bandwidth is always free.

Finally, because Emby is going in this direction of forcing Direct Stream over Direct Play in their app-store clients, I've been working on adding new options to the plugin.  Options such as black listings versions of the emby client  and blocking direct streaming.  I'm also working on code to handle preventing Emby from slurping down entire contents of "original" quality playback for Direct Stream, using a similar model like being used for Google Drive transcode streams.

**Comment by SteveMalso** [comment] 2018-05-17 15:27
Damn, that's game changing, I didn't know Emby had this capability. The things that discouraged me from using Emby over Kodi was the addition of a "middle man" (server, VPS etc), upload bandwidth usage and increased CPU load on my seedbox. In light of what you guys mentioned essentially makes Kodi redundant to me. I always playback my vids at original quality. I can't get resume support working with your Kodi addon and watched status isn't working 100%, both are big let-downs for me. So I'm definitely enticed to try out Emby now.

**Comment by fabioneves** [comment] 2018-05-17 15:52
@SteveMalso I'm using KODI with Emby, it's awesome with Embuary skin, you should try it. What I really like about it.. is that I use Kodi on my nVidia Shield and also on my Tablet, my resume points and what I've seen, it's all in sync, which is great! Good luck :)

**Comment by ddurdle** [comment] 2018-05-17 16:25
Most resume points playback issues are looking more related to the media.  When I worked on them in KODI, sometimes the amount of time between starting the movie and passing the player where to seek in the file made the difference between successfully resuming and starting from the beginning.  I use Google Transcode streams 95% of the time when I use KODI, and resume points ALWAYS work for me.  Google Transcode streams are instantly seekable and you don't have to do anything special to resume. 
 But if I used "original" quality and used more non-HLS files, I'd probably face more failures.  Some media files the player needs to read the headers and the start of the file and then seek to the end of the file to read meta information stored at the end of the file, and then seek back to the start.  Increases delay and delay causes the resume seek to fail.

With all that said, the KODI/MrMC connected to Emby, feeding Google Drive content via Direct Play original quality, I was able to seek within a movie successfully once and only been able to resume once as well.  I'll have to do the same tests later with the same movie, but the Google Transcode version to see if seeking works.

Emby solves my biggest gripe with KODI, which was the library.  I never had the time and patience to try to populate the KODI db with my library.  I have many devices and some I don't use often.  I don't have the patience for replicating the library before I can get into it to get something new I want to watch.  Also, most of my KODI devices are on Raspberry Pi boards.  In run all these boards in READ-ONLY mode, which means I can't use the library feature.  The Emby thrown in makes KODI a dream experience.  KODI is amazing for playing "anything".  Emby takes care of the indexing the library, storing my watch and resume status, and all the rest.

**Comment by fabioneves** [comment] 2018-05-17 16:34
@ddurdle resume points are working just fine for me with Emby / Kodi with original files 👍

**Comment by ddurdle** [comment] 2018-05-17 17:30
Good to hear.  I'll do some testing in KODI+Emby.

KODI or even MrMC is a better player then Emby.  I've been testing HEVC files on an ipad with the emby app, and it is consistently wanting to transcode to playback either 4k or 1080p.  I tested the same but through the MrMC app against the same Emby server with the same files, and it Direct Plays and has no issue playing back the 4K or 1080p HEVC.

I can always create a "slim" plugin for KODI that will allow Direct Play of Google Drive transcode streams, if the demand is there.  Google Drive transcode streams just need a player that can do a CORS  implementation (which KODI does).  The "slim" plugin would be nothing more then a few lines of code that handles the CORS logic.

**Comment by SteveMalso** [comment] 2018-05-18 09:40
Alrighty so I'm in the process of setting this up. I have videostream up and running, I can play videos in a web browser without issue. Is the Emby setup as simple as downloading Emby server and scanning STRMs into the library using the STRMs created by videostream? So far this is what I've done but when playing a video from my Emby library results in no playback, just endless spinning.

**Comment by SteveMalso** [comment] 2018-05-19 05:09
Do errors like the following cause bad performance/buffering?

Exception happened during processing of request from ('***********')
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/drivas/VideoStream/resources/libgui/webgui.py", line 192, in __ini                                                                             t__
    BaseHTTPRequestHandler.__init__(self, *args)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

**Comment by ddurdle** [comment] 2018-05-19 12:02
You have passthrough = true in settings?

What emby app and device are you playing back on?

The broken pipe errors are normal, indicators the connection was closed by the requestor.  Emby analyzes media for codec information using ffprobe and the connections are abandoned after the meta info is retrieved.

**Comment by ddurdle** [comment] 2018-05-19 12:44
Ah, yes, encrypted videos need to passthrough the server because the server needs to decrypt them for the player to play them back.  The decryption is done on-the-fly by the server.  It shouldn't take any additional resources, but it will use the upload bandwidth of the server.  

I only usually use encrypted videos for playback of security surveillance videos, and the performance is ok (1GB files).  I'd have to test with larger bitrate content (like a bluray raw movie).  There might be performance tweaks to increase performance.  I usually use a weak VPS server with slow disks, only 128mb ram, weak cpu, so that I ensure the decryption can work with least amount of resources.

For the no audio, what is the codec reported for the media (click on "nerds for stats") when playing back?   
 It could be using an audio codec not supported. I know my Google Chrome on Debian will not playback either DTS or TrueHD (no sound) -- only DD, AAC, AA3

It is also possible emby is trying to transcode the video.  Check the emby-server log directory when you playback to see if a ffmpeg-remux-* ffmpeg-directstream-*, ffmpeg-transcode-* file is created.  This would definitely account for performance issues.

I'm looking at creating a 'lite' version of a plugin that could be installed in KODI that would work with a Emby Server that is servicing Google Drive content.  This way one could enjoy the playback qualities of KODI but keep their media in Emby.  In the case of a 'lite' plugin, the plugin itself would do the decryption decoding (and that is about it).   This would allow for the Direct Play passthrough to work for encrypted files.

**Comment by SteveMalso** [comment] 2018-05-19 13:09
Understood. Disregard the audio issue, it was an issue with the video. 

Workaround for now I'm considering I'm using LibreELEC is to load VideoStream on it and also install Emby server on it. That way I can eliminate the middle man. Install the Emby for Kodi addon and hope that the resume and watched status marking functions work.

**Comment by ddurdle** [comment] 2019-03-13 15:22
completed.

**Closed by ddurdle** 2019-03-13 15:22 UTC
Labels: in testing, investigating
