### ISSUE TITLE
strm creation not inserting 'http://' at the start

### ISSUE THREAD

**Issue by marilson8** [ddurdle/Python-GoogleDrive-VideoStream#57] opened 2018-05-16 19:37 UTC
When exporting, the .strm file are not with http:// at the start, need to open the file and edit one by one

**Comment by ddurdle** [comment] 2018-05-16 20:15
Are you exporting just one file, or a directory of files?  Does it work for you when you use a scheduled task?

Are you using the latest code from github or are you using a zip file from releases folder (and if so, which version)?

I've been testing locally and on a server today and my STRM files have http:// in them.

**Comment by marilson8** [comment] 2018-05-16 20:20
i've tested exporting one file, as i had an updated library. I wanst using scheduled task. The test was from .zip file, GoogleDrive-VideoStream-0.1.20.zip	v0.1.20 (2018-05-12)	5 days ago. Sry for my poor english

**Comment by ddurdle** [comment] 2018-05-18 17:14
confirmed.  It only happens when generating 1 STRM (not when generating STRMs by folder or account).  Thank you for reporting the issue.  It is now fixed in latest git and 0.1.23

**Comment by marilson8** [comment] 2018-05-18 18:09
Thanx, i'll test soon. How about the schedule task, i tried yesterday, but, the files didnt sync with the local folder, tested within the latest commit and the other releases, none erro appear in prompt. Maybe was  wrong manipulation by me, how it works?

**Comment by ddurdle** [comment] 2018-05-18 18:36
What does it show when you got to [scheduled tasks]?  Does it list the scheduled job you created?  Does it show a last run time?  Does it show STRMs were created or "exception"?

**Comment by marilson8** [comment] 2018-05-18 23:20
it only shows as: never ran job, all the time after created.

**Comment by ddurdle** [comment] 2018-05-18 23:40
try restarting the plugin service.

**Comment by marilson8** [comment] 2018-05-20 15:47
It works on the lastest .zip, but, the directorys are duplicating, an example:

duplicating:
C:\strm\Series\Animes\Dragon Ball Z\1 Temporada\Series\Animes\Dragon Ball Z\1 Temporada

must be like:
C:\strm\Series\Animes\Dragon Ball Z\1 Temporada

**Comment by marilson8** [comment] 2018-05-21 12:58
Tried here, and it now only generate 1 file called: .strm in the folder. The option to choose between: root and the others accounts are gone, maybe this is the cause? or another thing

![image](https://user-images.githubusercontent.com/22123799/40308689-0e6a2e42-5cd5-11e8-8c79-28ee9a2d4405.png)

![image](https://user-images.githubusercontent.com/22123799/40308708-193a2926-5cd5-11e8-8491-373d10877f5b.png)

**Comment by ddurdle** [comment] 2018-05-21 23:20
Thank you for sharing the command (shown in screenshot).  I will try to replicate the problem based on the choices you made at the settings screen.

**Comment by ddurdle** [comment] 2018-05-23 23:48
Fixed the missing parameter.  I think it was the cause because I'm able to generate without error after fixing that.

**Comment by marilson8** [comment] 2018-05-24 11:32
worked perfetctly, and now, its really really fast, thanx so much for this

**Comment by marilson8** [comment] 2018-09-28 04:52
> Fixed the missing parameter. I think it was the cause because I'm able to generate without error after fixing that.

Hey ddurdle, long time han?!, hey, i lost this update from my pc, I tested the version around this date 23 of may, and none works exacly like before, could u point me the version above for download?

**Comment by marilson8** [comment] 2018-09-28 05:47
I looked back and found it, ty anyway brother S2

**Comment by ddurdle** [comment] 2019-03-13 15:19
completed.

**Closed by ddurdle** 2019-03-13 15:19 UTC
Labels: in testing
